import {
  Activity,
  Bike,
  BookOpen,
  Brain,
  Coffee,
  Dumbbell,
  Flame,
  Footprints,
  Heart,
  Moon,
  Music,
  Pencil,
  Pill,
  Smile,
  Sun,
  Timer,
  Droplets,
  Utensils,
  Wind,
  Zap,
  TreePine,
  Dog,
  Waves,
  Eye,
  type LucideIcon,
} from "lucide-react";

export const ACTIVITY_ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  bike: Bike,
  book: BookOpen,
  brain: Brain,
  coffee: Coffee,
  dumbbell: Dumbbell,
  flame: Flame,
  footprints: Footprints,
  heart: Heart,
  moon: Moon,
  music: Music,
  pencil: Pencil,
  pill: Pill,
  smile: Smile,
  sun: Sun,
  timer: Timer,
  water: Droplets,
  utensils: Utensils,
  wind: Wind,
  zap: Zap,
  tree: TreePine,
  dog: Dog,
  waves: Waves,
  eye: Eye,
};

export const ACTIVITY_ICON_OPTIONS = Object.keys(ACTIVITY_ICON_MAP);
